src/Entity/Book.php
<?php

namespace App\Entity;

use App\Repository\BookRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: BookRepository::class)]
class Book
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\ManyToOne(targetEntity: Category::class, inversedBy: 'books')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Category $category = null;

    #[ORM\Column]
    private ?int $pages = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $publication_date = null;

    #[ORM\Column]
    private ?\DateTime $created_at = null;

    #[ORM\Column]
    private ?\DateTime $updated_at = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): static
    {
        $this->category = $category;

        return $this;
    }

    public function getPages(): ?int
    {
        return $this->pages;
    }

    public function setPages(int $pages): static
    {
        $this->pages = $pages;

        return $this;
    }

    public function getPublicationDate(): ?\DateTimeInterface
    {
        return $this->publication_date;
    }

    public function setPublicationDate(\DateTimeInterface $publication_date): static
    {
        $this->publication_date = $publication_date;

        return $this;
    }

    public function getCreatedAt(): ?\DateTime
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTime $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTime
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTime $updated_at): static
    {
        $this->updated_at = $updated_at;

        return $this;
    }
}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use App\Repository\BookReadRepository;
use App\Repository\BookRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\HttpFoundation\Request;
use App\Entity\BookRead;
use App\Entity\User;

class HomeController extends AbstractController
{
    private BookReadRepository $bookReadRepository;
    private BookRepository $bookRepository;
    private EntityManagerInterface $entityManager;

    public function __construct(BookReadRepository $bookReadRepository, BookRepository $bookRepository, EntityManagerInterface $entityManager)
    {
        $this->bookReadRepository = $bookReadRepository;
        $this->bookRepository = $bookRepository;
        $this->entityManager = $entityManager;
    }

    #[Route('/', name: 'app.home')]
    public function index(): Response
    {
        $user = $this->getUser();

        if (!$user instanceof User) {
            return $this->redirectToRoute('auth.login');
        }

        $userId = $user->getId();
        $allbooks = $this->bookRepository->findAll();
        $booksReading = $this->bookReadRepository->findByUserId($userId, false);
        $booksRead = $this->bookReadRepository->findByUserId($userId, true);

        foreach ($booksReading as $bookread) {
            $books = $this->bookRepository->find($bookread->getBookId());
            if ($books) {
                $book[$bookread->getBookId()] = $books;
            }
        }

        foreach ($booksRead as $bookread) {
            $books = $this->bookRepository->find($bookread->getBookId());
            if ($books) {
                $book[$bookread->getBookId()] = $books;
            }
        }

        $categoryCounts = [];
        foreach ($allbooks as $dataRadar) {
            $categoryName = $dataRadar->getCategory()->getName();
            if (!isset($categoryCounts[$categoryName])) {
                $categoryCounts[$categoryName] = 0;
            }
            $categoryCounts[$categoryName]++;
        }
        $categories = array_keys($categoryCounts);
        $dataPoints = array_values($categoryCounts);

        return $this->render('pages/home.html.twig', [
            'allbooks' => $allbooks,
            'books' => $book,
            'booksReading' => $booksReading,
            'booksRead' => $booksRead,
            'name' => 'Accueil',
            'categories' => $categories, 
            'dataPoints' => $dataPoints,
        ]);
    }

    #[Route('/add-book-read', name: 'app.add_book_read', methods: ['POST'])]
    public function addBookRead(Request $request): Response
    {
        $user = $this->getUser();
        if (!$user instanceof User) {
            return $this->redirectToRoute('auth.login');
        }

        $bookRead = new BookRead();
        $bookRead->setUserId($user->getId());
        $bookRead->setBookId($request->request->get('book_id'));
        $bookRead->setRating($request->request->get('rating'));
        $bookRead->setDescription($request->request->get('description'));
        $bookRead->setRead($request->request->get('is_read') ? true : false);
        $bookRead->setCreatedAt(new \DateTime());
        $bookRead->setUpdatedAt(new \DateTime());

        $this->entityManager->persist($bookRead);
        $this->entityManager->flush();

        return $this->redirectToRoute('app.home');
    }
}

templates/components/home/booksRead.html.twig
<div class="card card-grid h-full min-w-full">
    <div class="card-header">
        <h3 class="card-title">
            Mes lectures terminées
        </h3>
        <div class="input input-sm max-w-48">
            <i class="ki-filled ki-magnifier">
            </i>
            <input data-datatable-search="#read-books-table" placeholder="Rechercher" type="text"/>
        </div>
    </div>
    <div class="card-body">
        <div id="read-books-table" data-datatable="true" data-datatable-page-size="5">
            <div class="scrollable-x-auto">
                <table class="table table-border" data-datatable-table="true">
                    <thead>
                    <tr>
                        <th class="min-w-[280px]">
                            <span class="sort asc">
                                <span class="sort-label">Livre</span>
                                <span class="sort-icon"></span>
                            </span>
                        </th>
                        <th class="min-w-[135px]">
                            <span class="sort asc">
                                <span class="sort-label">Catégorie</span>
                                <span class="sort-icon"></span>
                            </span>
                        </th>
                        <th class="min-w-[135px]">
                            <span class="sort asc">
                                <span class="sort-label">Note</span>
                                <span class="sort-icon"></span>
                            </span>
                        </th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for bookRead in booksRead %}
                        {% set book = books[bookRead.getBookId()] %}
                    <tr>
                        <td>
                            <div class="flex flex-col gap-2">
                                <a class="leading-none font-medium text-sm text-gray-900 hover:text-primary" href="#">
                                    {{ book.name }}
                                </a>
                                <span class="text-2sm text-gray-700 font-normal leading-3">
                                    {{ book.description }}
                                </span>
                            </div>
                        </td>
                        <td>{{ book.category.name }}</td>
                        <td>
                            <div class="rating">
                                {% for i in 1..5 %}
                                    <div class="rating-label {% if i <= bookRead.getRating() %}checked{% endif %}">
                                        <i class="rating-on ki-solid ki-star text-base leading-none"></i>
                                        <i class="rating-off ki-outline ki-star text-base leading-none"></i>
                                    </div>
                                {% endfor %}
                            </div>
                        </td>
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="card-footer justify-center md:justify-between flex-col md:flex-row gap-5 text-gray-600 text-2sm font-medium">
                <div class="flex items-center gap-2 order-2 md:order-1">
                    Show
                    <select class="select select-sm w-16" data-datatable-size="true" name="perpage">
                    </select>
                    per page
                </div>
                <div class="flex items-center gap-4 order-1 md:order-2">
                    <span data-datatable-info="true"></span>
                    <div class="pagination" data-datatable-pagination="true">
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

templates/components/home/booksReading.html.twig
<div class="card card-grid h-full min-w-full">
    <div class="card-header">
        <h3 class="card-title">
            Mes lectures en cours
        </h3>
        <div class="input input-sm max-w-48">
            <i class="ki-filled ki-magnifier">
            </i>
            <input data-datatable-search="#current-books-table" placeholder="Rechercher" type="text"/>
        </div>
    </div>
    <div class="card-body">
        <div id="current-books-table" data-datatable="true" data-datatable-page-size="5">
            <div class="scrollable-x-auto">
                <table  class="table table-border" data-datatable-table="true">
                    <thead>
                    <tr>
                        <th class="min-w-[280px]">
                            <span class="sort asc">
                                <span class="sort-label">Livre</span>
                                <span class="sort-icon"></span>
                            </span>
                        </th>
                        <th class="max-w-[135px] text-end">
                            <span class="sort">
                                <span class="sort-label">Modifié le</span>
                                <span class="sort-icon"></span>
                            </span>
                        </th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for bookRead in booksReading %}
                        {% set book = books [bookRead.getBookId()]%}
                        <tr>
                            <td>
                                <div class="flex flex-col gap-2">
                                    <a class="leading-none font-medium text-sm text-gray-900 hover:text-primary"
                                       href="#">
                                        {{book.name}}
                                    </a>
                                    <span class="text-2sm text-gray-700 font-normal leading-3">
                                        {{book.description}}
                                </span>
                                </div>
                            </td>
                            <td class="text-end">
                                {{ bookRead.updatedAt|date('d/m/Y à H:i') }}
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="card-footer justify-center md:justify-between flex-col md:flex-row gap-5 text-gray-600 text-2sm font-medium">
                <div class="flex items-center gap-4 order-1 md:order-2">
                    <span data-datatable-info="true"></span>
                    <div class="pagination" data-datatable-pagination="true"></div>
                </div>
            </div>
        </div>
    </div>
</div>

templates/components/home/radarChart.html.twig
<!DOCTYPE html>
<html>
<head>
    <title>Radar Chart</title>
    <script src="https://cdn.jsdelivr.net/npm/apexcharts"></script>
</head>
<body>
<div class="card h-full">
    <div class="card-header">
        <h3 class="card-title">
            Répartition de mes lectures
        </h3>
    </div>
    <div class="card-body flex flex-col gap-5">
        <div id="radarChart"></div>
    </div>
</div>

<script>
    // Extraire les données passées par le contrôleur
    const categories = {{ categories|json_encode|raw }};
    const dataPoints = {{ dataPoints|json_encode|raw }};

    var options = {
      series: [
        {
          name: "Livres lus par catégorie",
          data: dataPoints
        }
      ],
      chart: {
        height: 350,
        type: 'radar',
      },
      labels: categories,
      fill: {
        opacity: 0.5,
        colors: []
      },
      stroke: {
        show: true,
        width: 2,
        colors: [],
        dashArray: 0
      },
      markers: {
        size: 5,
        hover: {
          size: 10
        }
      },
      plotOptions: {
        radar: {
          polygons: {
            strokeColor: '#e8e8e8',
            fill: {
              colors: ['#f8f8f8', '#fff']
            }
          }
        }
      },
      yaxis: {
        labels: {
          style: {
            colors: ["#a8a8a8"],
            fontSize: "11px",
            fontFamily: 'Arial'
          }
        }
      }
    };

    var chart = new ApexCharts(document.querySelector("#radarChart"), options);
    chart.render();
</script>
</body>
</html>